
project_id = "wyjfdvmzwilcxwuoceti"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[[seed.tables]]
name = "profiles"

# Edge Functions
[functions.process-pdf]
verify_jwt = false

[functions.insert-extracted-data]
verify_jwt = false
