
project_id = "wyjfdvmzwilcxwuoceti"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true

[storage]
enabled = true

# Define functions that should be deployed
[functions]
# Previously there was a "serve" function that does not exist
# We're now defining the specific functions that do exist
